#exercise and diet logging system
while(True):
  print("\nFill in the details of your client's exercise and diet")
  l1=[[1,"Client_1"],[2,"Client_2"],[3,"Client_3"]]
  l2=[["a","exercise"],["b","diet"]]
  for number,name in l1:
    print("Type",number,"for",name)
  n1=int(input())
  if n1==1:
    print("Your selected client is Client_1\n")
    for alpha,activity in l2:
       print("Type", alpha,"for", activity)
    a1=input()
    if a1=="a":
        print("You wish to make changes in exercise tab/n")
        r1= open("Client_1 exercise.txt","a")
        print("please enter the date in dd/mm/yy format")
        d1=input()
        print("please enter the time in hh:min am/pm format")
        t1=input()
        print("please enter the exercise done")
        e1=input()
        a = r1.write(d1)
        d = r1.write("   ")
        b = r1.write(t1)
        e = r1.write("   ")
        c = r1.write(e1)
    elif a1=="b":
        print("You wish to make changes in diet tab\n")
        r1= open("Client_1 diet.txt","a")
        print("please enter the date in dd/mm/yy format")
        d1=input()
        print("please enter the time in hh:min am/pm format")
        t1=input()
        print("please enter the diet done")
        e1=input()
        a = r1.write(d1)
        d = r1.write("   ")
        b = r1.write(t1)
        e = r1.write("   ")
        c = r1.write(e1)
    else:
        print("sorry buy it seems you have entered a invalid input\n")
  elif n1==2:
    print("Your selected client is Client_2\n")
    for alpha,activity in l2:
       print("Type", alpha,"for", activity)
    a1=input()
    if a1=="a":
        print("You wish to make changes in exercise tab\n")
        r1= open("Client_2 exercise.txt","a")
        print("please enter the date in dd/mm/yy format")
        d1=input()
        print("please enter the time in hh:min am/pm format")
        t1=input()
        print("please enter the exercise done")
        e1=input()
        a = r1.write(d1)
        d = r1.write("   ")
        b = r1.write(t1)
        e = r1.write("   ")
        c = r1.write(e1)
    elif a1=="b":
        print("You wish to make changes in diet tab\n")
        r1 = open("Client_2 diet.txt", "a")
        print("please enter the date in dd/mm/yy format")
        d1 = input()
        print("please enter the time in hh:min am/pm format")
        t1 = input()
        print("please enter the diet done")
        e1 = input()
        a = r1.write(d1)
        d = r1.write("   ")
        b = r1.write(t1)
        e = r1.write("   ")
        c = r1.write(e1)
    else:
        print("sorry buy it seems you have entered a invalid input\n")
  elif n1==3:
    print("Your selected client is Client_3\n")
    for alpha,activity in l2:
       print("Type", alpha,"for", activity)
    a1=input()
    if a1=="a":
        print("You wish to make changes in exercise tab\n")
        r1 = open("Client_3 exercise.txt", "a")
        print("please enter the date in dd/mm/yy format")
        d1 = input()
        print("please enter the time in hh:min am/pm format")
        t1 = input()
        print("please enter the excercise done")
        e1 = input()
        a = r1.write(d1)
        d = r1.write("   ")
        b = r1.write(t1)
        e = r1.write("   ")
        c = r1.write(e1)
    elif a1=="b":
        print("You wish to make changes in diet tab\n")
        r1= open("Client_3 diet.txt","a")
        print("please enter the date in dd/mm/yy format")
        d1=input()
        print("please enter the time in hh:min am/pm format")
        t1=input()
        print("please enter the diet done")
        e1=input()
        a= r1.write(d1)
        d= r1.write("   ")
        b= r1.write(t1)
        e = r1.write("   ")
        c= r1.write(e1)
    else:
        print("sorry buy it seems you have entered a invalid input\n")
  else:
    print("sorry buy it seems you have entered a invalid input\n")